Calculator UI
omarsalem7/Math-Magicians pull request #2
Opened 2022-02-14 18:17 UTC by omarsalem7

I did the following in this PR:
- Delete all the boilerplate from CRA (text, images, styles).
- Create components directory, create a new Calculator.js file
- Create The UI for Calculator

2022-02-14 18:32 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @omarsalem7,

Good job so far!
✔️ Good documentation
✔️ App UI fits template design
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-14 18:32 UTC, TedLivist commented on README.md
> +# Math Magicians
- [ ] Kindly remove unused boilerplate files as they make your codebase look neater

  public folder | src folder
  :---:|:---:
  ![omar-public](https://user-images.githubusercontent.com/36542986/153923826-72777570-8499-4155-a32c-f64342b5c61c.jpg) | ![omar-src](https://user-images.githubusercontent.com/36542986/153923835-5fb7c049-a77b-4e03-930b-5414a724bd84.jpg)

2022-02-14 18:32 UTC, TedLivist commented on src/App.js
>  }
- [x] Your components should be class-based. This App component is function-based, kindly refactor a class-based component.

2022-02-15 08:34 UTC, omarsalem7 commented on src/App.js
>  }
Hello @TedLivist 
I changes your suggestion, you can check it now 
have a nice day 😄

2022-02-15 08:43 UTC, julie-ify approved these changes
## Hi @omarsalem7,

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 08:43 UTC, merged